name = "PlutoStartup"
uuid = "7fd7c61b-229c-4c29-8df5-3e433ba2eae1"
authors = ["Jason Eckstein <jekyllstein@gmail.com>"]
version = "0.1.0"

[deps]
Arrow = "69666777-d1a9-59fb-9406-91d4454c9d45"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FCANN = "8c01af00-eda8-11e9-3d27-59b8c7aa8fdd"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
HypertextLiteral = "ac1192a8-f4b3-4bfe-ba22-af5b92cd3ab2"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
NVIDIALibraries = "455bb3cc-869f-42f8-aad9-fcdd684af481"
NonTabularRL = "c7324298-1923-4c4f-bd91-98f34631c25c"
PlotlyJS = "f0f68f2c-4968-5e81-91da-67840de0976a"
Pluto = "c3e4b0f8-55cb-11ea-2926-15256bba5781"
PlutoDevMacros = "a0499f29-c39b-4c5c-807c-88074221b949"
PlutoHooks = "0ff47ea0-7a50-410d-8455-4348d5de0774"
PlutoPlotly = "8e989ff0-3d88-8e9f-f020-2b208a939ff0"
PlutoProfile = "ee419aa8-929d-45cd-acf6-76bd043cd7ba"
PlutoSliderServer = "2fc8631c-6f24-4c5b-bca7-cbb509c42db4"
PlutoUI = "7f904dfe-b85e-4ff6-b463-dae2292396a8"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
ProfileCanvas = "efd6af41-a80b-495e-886c-e51b0c7d77a3"
ProgressLogging = "33c8b6b6-d38a-422a-b730-caa89a2f386c"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
Serialization = "9e88b42a-f829-5b0c-bbe9-9e923198166b"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TabularRL = "70984187-0053-49a1-8db7-ddab96a995ff"
TailRec = "f6209947-f0a9-4a6b-8802-d6ceac74b6f9"
Transducers = "28d57a85-8fef-5791-bfe6-a80928e7c999"
